// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHarFYu94r98iIWapDaGBntBBbG6FCMtc',
    appId: '1:160368347836:web:1aa37f8cd4b8de69cf5eb9',
    messagingSenderId: '160368347836',
    projectId: 'chat-app-2023-9465a',
    authDomain: 'chat-app-2023-9465a.firebaseapp.com',
    storageBucket: 'chat-app-2023-9465a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_qn0cI1cLjmgEsuJXpUV0Qi_8Ow8qGcg',
    appId: '1:160368347836:android:af8de4a3edaa2e8dcf5eb9',
    messagingSenderId: '160368347836',
    projectId: 'chat-app-2023-9465a',
    storageBucket: 'chat-app-2023-9465a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAktjBIja2tFsSBNzLP4WeDI_LtpAHLioY',
    appId: '1:160368347836:ios:1d4bf0e4e7dd979ccf5eb9',
    messagingSenderId: '160368347836',
    projectId: 'chat-app-2023-9465a',
    storageBucket: 'chat-app-2023-9465a.appspot.com',
    iosClientId: '160368347836-gctt2d5gaoiekpc9ic75k1uk75oc4vlh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAktjBIja2tFsSBNzLP4WeDI_LtpAHLioY',
    appId: '1:160368347836:ios:1d4bf0e4e7dd979ccf5eb9',
    messagingSenderId: '160368347836',
    projectId: 'chat-app-2023-9465a',
    storageBucket: 'chat-app-2023-9465a.appspot.com',
    iosClientId: '160368347836-gctt2d5gaoiekpc9ic75k1uk75oc4vlh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
